config/routes.rb
KeynoteLogger::Application.routes.draw do
  resources :logs do
    resources :requests
    resources :notices
  end

  root :to => 'logs#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
  has_many :requests, :dependent => :destroy
  has_many :notices,  :dependent => :destroy
  attr_accessible :ip, :token

  validates :token, :presence => true, :uniqueness => true, :length => { :minimum => 5 }
  validates :ip, :format => { :with => /([0-9]{1,3}\.){3}[0-9]{1,3}/, :message => "Not a valid IP" }

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :log
  attr_accessible :detail
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :log
  attr_accessible :content, :error_code, :header, :ip, :type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new
    @log.ip = request.remote_ip

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(params[:log])
    @log.ip = request.remote_ip

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    @log = Log.find(params[:log_id])
    @notices = @log.notices

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @log = Log.find(params[:log_id])
    @notice = @log.notices.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @log = Log.find(params[:log_id])
    @notice = Notice.new
    @notice.log_id = @log.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @log = Log.find(params[:log_id])
    @notice = Log.notices.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @log = Log.find(params[:log_id])
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @log = Log.find(params[:log_id])
    @notice = Log.notices.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @log = Log.find(params[:log_id])
    @notice = Log.notices.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    @log = Log.find(params[:log_id])
    @requests = @log.requests

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @log = Log.find(params[:log_id])
    #@request = Request.find(params[:id])
    @request = @log.requests.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @log = Log.find(params[:log_id])
    @request = Request.new
    @request.log_id = params[:log_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @log = Log.find(params[:log_id])
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @log = Log.find(params[:log_id])
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @log = Log.find(params[:log_id])
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @log = Log.find(params[:log_id])
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KeynoteLogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <tr>
    <th>Token</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.token %></td>
    <td><%= log.ip %></td>
    <td><%= link_to 'Show', log %></td>
    <td><%= link_to 'Edit', edit_log_path(log) %></td>
    <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= @log.token %>
</p>

<p>
  <b>Ip:</b>
  <%= @log.ip %>
</p>


<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

app/views/notices/_form.html.erb
<%= form_for([@log,@notice]) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :log_id %><br />
    <%= f.text_field :log_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', [@log,@notice] %> |
<%= link_to 'Back', log_notices_path %>

app/views/notices/index.html.erb
<h1>Listing notices</h1>

<table>
  <tr>
    <th>Detail</th>
    <th>Type</th>
    <th>Log</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notices.each do |notice| %>
  <tr>
    <td><%= notice.detail %></td>
    <td><%= notice.type %></td>
    <td><%= notice.log %></td>
    <td><%= link_to 'Show', [@log,notice] %></td>
    <td><%= link_to 'Edit', edit_log_notice_path(@log, notice) %></td>
    <td><%= link_to 'Destroy', [@log,notice], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notice', new_log_notice_path %>

app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', log_notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Detail:</b>
  <%= @notice.detail %>
</p>

<p>
  <b>Type:</b>
  <%= @notice.type %>
</p>

<p>
  <b>Log:</b>
  <%= @notice.log %>
</p>


<%= link_to 'Edit', edit_log_notice_path(@log,@notice) %> |
<%= link_to 'Back', log_notices_path %>

app/views/requests/_form.html.erb
<%= form_for([@log,@request]) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :header %><br />
    <%= f.text_field :header %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :error_code %><br />
    <%= f.text_field :error_code %>
  </div>
  <div class="field">
    <%= f.label :log_id %><br />
    <%= f.text_field :log_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', [@log,@request] %> |
<%= link_to 'Back', log_requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <tr>
    <th>Ip</th>
    <th>Type</th>
    <th>Header</th>
    <th>Content</th>
    <th>Error code</th>
    <th>Log</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.ip %></td>
    <td><%= request.type %></td>
    <td><%= request.header %></td>
    <td><%= request.content %></td>
    <td><%= request.error_code %></td>
    <td><%= request.log_id %></td>
    <td><%= link_to 'Show', [@log,request] %></td>
    <td><%= link_to 'Edit', edit_log_request_path(@log,request) %></td>
    <td><%= link_to 'Destroy', [@log,request], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_log_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', log_requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>IP:</b>
  <%= @request.ip %>
</p>

<p>
  <b>Type:</b>
  <%= @request.type %>
</p>

<p>
  <b>Header:</b>
  <%= @request.header %>
</p>

<p>
  <b>Content:</b>
  <%= @request.content %>
</p>

<p>
  <b>Error code:</b>
  <%= @request.error_code %>
</p>

<p>
  <b>Log:</b>
  <%= @request.log_id %>
</p>


<%= link_to 'Edit', edit_log_request_path(@log, @request) %> |
<%= link_to 'Back', log_requests_path %>